"""fix_name_fields

Revision ID: a63de3aebf0e
Revises: 17ba7fc62ecd
Create Date: 2025-01-22 20:16:00.020704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63de3aebf0e'
down_revision: Union[str, None] = '17ba7fc62ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('name', sa.String(length=80), nullable=False))
    op.drop_index('ix_attendee_nombre', table_name='attendee')
    op.create_index(op.f('ix_attendee_name'), 'attendee', ['name'], unique=True)
    op.drop_column('attendee', 'nombre')
    op.add_column('sessionevent', sa.Column('name', sa.String(length=80), nullable=False))
    op.drop_index('ix_sessionevent_nombre', table_name='sessionevent')
    op.create_index(op.f('ix_sessionevent_name'), 'sessionevent', ['name'], unique=True)
    op.drop_column('sessionevent', 'nombre')
    op.add_column('speaker', sa.Column('name', sa.String(length=80), nullable=False))
    op.drop_index('ix_speaker_nombre', table_name='speaker')
    op.create_index(op.f('ix_speaker_name'), 'speaker', ['name'], unique=True)
    op.drop_column('speaker', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_speaker_name'), table_name='speaker')
    op.create_index('ix_speaker_nombre', 'speaker', ['nombre'], unique=True)
    op.drop_column('speaker', 'name')
    op.add_column('sessionevent', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sessionevent_name'), table_name='sessionevent')
    op.create_index('ix_sessionevent_nombre', 'sessionevent', ['nombre'], unique=True)
    op.drop_column('sessionevent', 'name')
    op.add_column('attendee', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_attendee_name'), table_name='attendee')
    op.create_index('ix_attendee_nombre', 'attendee', ['nombre'], unique=True)
    op.drop_column('attendee', 'name')
    # ### end Alembic commands ###
