"""Add owner event

Revision ID: be23bb4a52e8
Revises: 262f6e331944
Create Date: 2025-01-22 12:11:05.965449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be23bb4a52e8'
down_revision: Union[str, None] = '262f6e331944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'owner')
    # ### end Alembic commands ###
